/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TasksIndexImport } from './routes/tasks/index'
import { Route as TasksIdImport } from './routes/tasks/$id'

// Create/Update Routes

const TasksIndexRoute = TasksIndexImport.update({
  path: '/tasks/',
  getParentRoute: () => rootRoute,
} as any)

const TasksIdRoute = TasksIdImport.update({
  path: '/tasks/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdImport
      parentRoute: typeof rootRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  TasksIdRoute,
  TasksIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/tasks/$id",
        "/tasks/"
      ]
    },
    "/tasks/$id": {
      "filePath": "tasks/$id.tsx"
    },
    "/tasks/": {
      "filePath": "tasks/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
